from crewai.tools import BaseTool
from pydantic import BaseModel, Field
import difflib

# =====================================================================
# 1. ІНСТРУМЕНТ ПЕРЕВІРКИ ПЛАГІАТУ (Для Editor QA)
# =====================================================================
class SimilarityInput(BaseModel):
    source_text: str = Field(..., description="The raw source text from the manufacturer.")
    generated_text: str = Field(..., description="The text generated by the copywriter.")

class ContentSimilarityTool(BaseTool):
    name: str = "Similarity Checker"
    description: str = "Compares generated text against the original source to ensure it is not plagiarized. Target is >80% uniqueness."
    args_schema: type[BaseModel] = SimilarityInput

    def _run(self, source_text: str, generated_text: str) -> str:
        # 1. Захист від того, що LLM передасть None або не рядок
        source_text = str(source_text)
        generated_text = str(generated_text)

        # 2. НОРМАЛІЗАЦІЯ: Зводимо до нижнього регістру і прибираємо зайві пробіли/ентери
        norm_source = " ".join(source_text.lower().split())
        norm_generated = " ".join(generated_text.lower().split())
        
        # 3. Захист від порожніх вхідних даних
        if not norm_source or not norm_generated:
            return "FAILED. Uniqueness check failed because one of the input texts is empty."

        # 4. Обчислення на очищених даних
        similarity_ratio = difflib.SequenceMatcher(None, norm_source, norm_generated).ratio()
        uniqueness = (1 - similarity_ratio) * 100
        
        if uniqueness < 80:
            return f"FAILED. Uniqueness is {uniqueness:.2f}%. The text is too similar to the original. Please rewrite."
            
        return f"PASSED. Uniqueness is {uniqueness:.2f}%. The text is sufficiently original."


# =====================================================================
# 2. ІНСТРУМЕНТ ТОЧНОЇ КОНВЕРТАЦІЇ ДЛЯ США (Для Localizer US)
# =====================================================================
class ConversionInput(BaseModel):
    value: float = Field(..., description="The numerical value to convert (e.g., 300.5).")
    unit: str = Field(..., description="The metric unit of the value. Must be 'mm', 'cm', or 'kg'.")

class USMeasurementCalculatorTool(BaseTool):
    name: str = "US Measurement Calculator"
    description: str = "Calculates exact Imperial conversions for Dimensions (mm/cm -> inches) and Weight (kg -> lbs). Returns the formatted string combining both (e.g., '11.81\" (300 mm)'). Use this STRICTLY for Printer Dimensions, Build Volume, and Weight. Do NOT use for Nozzle size, Filament size, or Temperatures."
    args_schema: type[BaseModel] = ConversionInput

    def _run(self, value: float, unit: str) -> str:
        unit = unit.strip().lower()
        
        try:
            val = float(value)
        except ValueError:
            return "Error: Please provide a valid number for 'value'."

        if unit == 'mm':
            inches = round(val / 25.4, 2)
            # Прибираємо нулі після коми, якщо число ціле (напр. 11.0 -> 11)
            inches_str = f"{int(inches)}" if inches.is_integer() else str(inches)
            val_str = f"{int(val)}" if val.is_integer() else str(val)
            return f"{inches_str}\" ({val_str} mm)"
            
        elif unit == 'cm':
            inches = round(val / 2.54, 2)
            inches_str = f"{int(inches)}" if inches.is_integer() else str(inches)
            val_str = f"{int(val)}" if val.is_integer() else str(val)
            return f"{inches_str}\" ({val_str} cm)"
            
        elif unit == 'kg':
            lbs = round(val * 2.20462, 2)
            lbs_str = f"{int(lbs)}" if lbs.is_integer() else str(lbs)
            val_str = f"{int(val)}" if val.is_integer() else str(val)
            return f"{lbs_str} lbs ({val_str} kg)"
            
        else:
            return "Error: Unsupported unit. Only 'mm', 'cm', and 'kg' are allowed for conversion."