"""
Custom Tools for CrewAI Content Generation Pipeline v2.0

Інструменти:
1. ContentSimilarityTool — перевірка плагіату (Editor QA)
2. USMeasurementCalculatorTool — batch-конвертація метрика→Imperial (Localizer US)
"""

from crewai.tools import BaseTool
from pydantic import BaseModel, Field
from typing import ClassVar, Dict, List, Optional
import difflib
import re
import logging

logger = logging.getLogger(__name__)


# =====================================================================
# 1. ІНСТРУМЕНТ ПЕРЕВІРКИ ПЛАГІАТУ (Editor QA)
# =====================================================================

class SimilarityInput(BaseModel):
    source_text: str = Field(
        ...,
        description=(
            "The raw source text from the manufacturer. "
            "This is the ORIGINAL text to compare against."
        )
    )
    generated_text: str = Field(
        ...,
        description=(
            "The text generated by the copywriter. "
            "This is the NEW text being checked for plagiarism."
        )
    )


class ContentSimilarityTool(BaseTool):
    name: str = "Similarity Checker"
    description: str = (
        "Compares the copywriter's generated text against the original manufacturer source text "
        "to measure plagiarism. Returns PASSED (>80% unique) or FAILED (<80% unique). "
        "IMPORTANT: Pass the RAW SOURCE as 'source_text' and the COPYWRITER'S DRAFT as 'generated_text'. "
        "Both inputs must be plain text strings, not dicts or lists."
    )
    args_schema: type[BaseModel] = SimilarityInput

    # Мінімальна довжина тексту для осмисленого порівняння
    MIN_TEXT_LENGTH: ClassVar[int] = 50
    # Ліміт символів для difflib (O(N²) складність)
    MAX_COMPARISON_LENGTH: ClassVar[int] = 20000
    # Поріг унікальності
    UNIQUENESS_THRESHOLD: ClassVar[float] = 80.0

    def _clean_text(self, text: str) -> str:
        """Видаляє HTML-теги, нормалізує пробіли, зводить до lowercase."""
        # Захист типів (LLM іноді передає dict/list)
        text = str(text)
        # Видаляємо HTML-теги (щоб <div>, <strong> не завищували унікальність)
        text = re.sub(r'<[^>]+>', ' ', text)
        # Видаляємо URL (вони однакові в обох текстах — не показник плагіату)
        text = re.sub(r'https?://\S+', '', text)
        # Нормалізуємо пробіли та нижній регістр
        return " ".join(text.lower().split())

    def _run(self, source_text: str, generated_text: str) -> str:
        clean_source = self._clean_text(source_text)
        clean_generated = self._clean_text(generated_text)

        # Захист від порожніх/дуже коротких текстів
        if len(clean_source) < self.MIN_TEXT_LENGTH:
            return (
                "WARNING: Source text is too short for meaningful comparison "
                f"({len(clean_source)} chars). Cannot determine uniqueness. "
                "Proceeding with manual review recommended."
            )
        if len(clean_generated) < self.MIN_TEXT_LENGTH:
            return (
                "FAILED. Generated text is too short for meaningful comparison "
                f"({len(clean_generated)} chars). The copywriter must produce more content."
            )

        # CPU Guardrail: обрізаємо для difflib
        capped_source = clean_source[:self.MAX_COMPARISON_LENGTH]
        capped_generated = clean_generated[:self.MAX_COMPARISON_LENGTH]

        # Обчислення схожості
        similarity_ratio = difflib.SequenceMatcher(
            None, capped_source, capped_generated
        ).ratio()
        uniqueness = (1 - similarity_ratio) * 100

        # Додаткова метрика: n-gram overlap (ловить перефразування з тим же порядком слів)
        source_ngrams = self._get_ngrams(capped_source, n=4)
        generated_ngrams = self._get_ngrams(capped_generated, n=4)
        if source_ngrams and generated_ngrams:
            overlap = len(source_ngrams & generated_ngrams) / len(generated_ngrams) * 100
        else:
            overlap = 0.0

        # Формуємо вердикт
        if uniqueness < self.UNIQUENESS_THRESHOLD:
            return (
                f"FAILED. Uniqueness is {uniqueness:.1f}% (threshold: {self.UNIQUENESS_THRESHOLD}%). "
                f"4-gram overlap: {overlap:.1f}%. "
                "The text is too similar to the original. You MUST rewrite it significantly. "
                "Focus on restructuring paragraphs and using your own phrasing."
            )

        # Додаткова перевірка: навіть при високій "унікальності" за difflib,
        # якщо n-gram overlap > 40%, текст може бути lazy paraphrase
        if overlap > 40:
            return (
                f"WARNING. Uniqueness is {uniqueness:.1f}% (passes threshold), "
                f"BUT 4-gram overlap is {overlap:.1f}% — this suggests lazy paraphrasing. "
                "Consider restructuring the paragraph order and sentence patterns."
            )

        return (
            f"PASSED. Uniqueness is {uniqueness:.1f}%. "
            f"4-gram overlap: {overlap:.1f}%. The text is sufficiently original."
        )

    @staticmethod
    def _get_ngrams(text: str, n: int = 4) -> set:
        """Генерує множину n-грам зі слів тексту."""
        words = text.split()
        if len(words) < n:
            return set()
        return {tuple(words[i:i + n]) for i in range(len(words) - n + 1)}


# =====================================================================
# 2. ІНСТРУМЕНТ КОНВЕРТАЦІЇ ДЛЯ США (Localizer US)
# =====================================================================

class SingleConversion(BaseModel):
    """Одна одиниця для конвертації."""
    value: float = Field(..., description="Numerical value to convert (e.g., 300.5)")
    unit: str = Field(..., description="Metric unit: 'mm', 'cm', or 'kg'")
    label: Optional[str] = Field(
        default=None,
        description="Optional label for context (e.g., 'Width', 'Weight')"
    )


class ConversionInput(BaseModel):
    """Вхідна схема — підтримує як одне, так і кілька значень."""
    conversions: List[SingleConversion] = Field(
        ...,
        description=(
            "List of values to convert. Example: "
            "[{\"value\": 300, \"unit\": \"mm\", \"label\": \"Width\"}, "
            "{\"value\": 14.5, \"unit\": \"kg\", \"label\": \"Weight\"}]"
        ),
        min_length=1,
        max_length=20
    )


class USMeasurementCalculatorTool(BaseTool):
    name: str = "US Measurement Calculator"
    description: str = (
        "Calculates exact Imperial conversions for multiple values at once. "
        "Supports: mm→inches, cm→inches, kg→lbs. "
        "Returns formatted strings like '11.81\" (300 mm)' or '31.97 lbs (14.5 kg)'. "
        "Use STRICTLY for: Printer Dimensions, Build Volume, and Weight. "
        "Do NOT use for: Nozzle diameter, Filament diameter, Temperatures, or Print Speed. "
        "Pass ALL values in a single call using the 'conversions' array to avoid multiple tool calls."
    )
    args_schema: type[BaseModel] = ConversionInput

    # Коефіцієнти конвертації
    CONVERSION_FACTORS: ClassVar[Dict] = {
        'mm': {'factor': 1 / 25.4, 'imperial_unit': '"', 'metric_unit': 'mm'},
        'cm': {'factor': 1 / 2.54, 'imperial_unit': '"', 'metric_unit': 'cm'},
        'kg': {'factor': 2.20462, 'imperial_unit': ' lbs', 'metric_unit': 'kg'},
    }

    def _format_number(self, val: float) -> str:
        """Форматує число: 11.0 → '11', 11.81 → '11.81'."""
        return f"{int(val)}" if val == int(val) else f"{val}"

    def _convert_single(self, value: float, unit: str, label: Optional[str]) -> str:
        """Конвертує одне значення."""
        unit = str(unit).strip().lower()

        try:
            val = float(value)
        except (ValueError, TypeError):
            prefix = f"{label}: " if label else ""
            return f"{prefix}Error — invalid numerical value '{value}'"

        conv = self.CONVERSION_FACTORS.get(unit)
        if not conv:
            prefix = f"{label}: " if label else ""
            return (
                f"{prefix}Error — unsupported unit '{unit}'. "
                f"Only {list(self.CONVERSION_FACTORS.keys())} are allowed."
            )

        imperial_val = round(val * conv['factor'], 2)
        result = (
            f"{self._format_number(imperial_val)}{conv['imperial_unit']} "
            f"({self._format_number(val)} {conv['metric_unit']})"
        )

        if label:
            return f"{label}: {result}"
        return result

    def _run(self, conversions: list) -> str:
        """Обробляє batch конвертацій."""
        # Захист: LLM іноді передає dict замість list
        if isinstance(conversions, dict):
            conversions = [conversions]

        results = []
        for item in conversions:
            if isinstance(item, dict):
                val = item.get('value', 0)
                unit = item.get('unit', '')
                label = item.get('label')
            elif isinstance(item, SingleConversion):
                val = item.value
                unit = item.unit
                label = item.label
            else:
                results.append(f"Error — unexpected input format: {type(item)}")
                continue

            results.append(self._convert_single(val, unit, label))

        return "\n".join(results)